name: GitHub Actions
run-name: Running necessary checks ğŸš€
on: [push]
jobs:
  Code-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: ğŸšš Installing dependencies
        run: yarn 
      - name: ğŸ·ï¸ running typecheck
        run: yarn build
      - name: ğŸ§ª Running tests
        run: yarn test
      - name: ğŸš¨ Linting code
        run: yarn lint
      - name: ğŸš¨ prettier check code
        run: yarn format:check
