name: GitHub Actions
run-name: Running necessary checks ğŸš€
on: [push]
jobs:
  Code-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: ğŸ“¦ Install pnpm
        uses: pnpm/action-setup@v4
      - name: ğŸšš Installing dependencies
        run: pnpm install
      - name: ğŸ·ï¸ running typecheck
        run: pnpm build
      - name: ğŸ§ª Running tests
        run: pnpm test
      - name: ğŸš¨ Linting code
        run: pnpm lint
      - name: ğŸš¨ prettier check code
        run: pnpm format:check
